project:
  type: website
  output-dir: docs

website:
  title: "Jiayi’s website"
  navbar:
    left:
      - href: index.qmd
        text: About
      - href: resume.qmd
        text: Resume
      - text: Projects
        menu:
          - href: blog/hw1.qmd
            text: hw1
          - href: blog/hw2.qmd
            text: hw2
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
