project:
  type: website
  output-dir: docs
website:
  title: "Jiayi's website"
  navbar:
    left:
      - href: index.qmd
        text: About 
      - resume.qmd
      - href: blog.qmd
        text: Projects

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

